[advisories]
unmaintained = "workspace"
unsound = "all"
ignore = []

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
