[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
highlight = "all"
skip-tree = [
    # pulled in by tracing
    { name = "matchers" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-git = []
